package com.example.mydoc.models.enums;

public enum SpecialtyType {
    IMMUNOLOGY, ANESTHESIOLOGY, DERMATOLOGY, RADIOLOGY, OPHTHALMOLOGY,
    PEDIATRICS, REHABILITATION, PSYCHIATRY, ONCOLOGY, UROLOGY
}
